RaceHorology/ClassesAndGroupsUC.xaml, RaceHorology/ClassesAndGroupsUC.xaml.cs, RaceHorologyLib/AppDataModelDataTypes.cs, RaceHorologyLib/ClassesGroupsCategories.cs, RaceHorologyLib/RaceHorologyLib.csproj, RaceHorologyLibTest/ClassesGroupsCategoriesTest.cs, RaceHorologyLibTest/RaceHorologyLibTest.csproj
=> Fixing issue #105

RaceHorology/App.config, RaceHorology/MainWindow.xaml.cs, RaceHorology/Properties/Settings.Designer.cs, RaceHorology/Properties/Settings.settings, RaceHorology/Settings.xaml, RaceHorology/Settings.xaml.cs, RaceHorologyLib/LiveTimingMeasurement.cs
Teilnehmer werden hinzugefügt in der Form: 
- Name: "Automatisch",
- Firstname: "Erzeugt"
- Startnummer entsprechend der Zeitnahme
Kann ein und ausgeschaltet werden via Setting.
=> Implemention of issue #152, Unbekannte läufer automatisch hinzufügen

RaceHorology/CompetitionUC.xaml.cs, RaceHorologyLib/AppDataModelDataTypes.cs, RaceHorologyLib/DSVInterfaceModel.cs, RaceHorologyLib/Import.cs, RaceHorologyLibTest/AppDataModelTypesTest.cs, RaceHorologyLibTest/DSVImportTest.cs
Fixes issue #160
Check whether a participant is in the DSV list checks several fields.
If not, entry is marked red in participant list.
=> Checking all fields whether participant is the DSV list

.github/workflows/main.yml, RaceHorology/DSVImportUC.xaml, RaceHorology/DSVImportUC.xaml.cs, RaceHorologyLib/DSVImport.cs, RaceHorologyLibTest/DSVImportTest.cs
According to issue #168
- Die Import-Liste zeigt bei noch nicht importierter Datei "XXX" - schöner wäre etwas aussagekräftigeres.
- Formatierung der Punkteliste soll auf zwei Nchkommastellen sein.
- Problem mit Import "F": Vorschlag Workaround ersetze "F" mit "W" (später: Erstellen der Kategorien automatisieren)
=> Some minor DSV improvements

RaceHorology/MainWindow.xaml.cs, RaceHorologyLib/ALGETdC8001TimeMeasurement.cs
=> Store the ALGE logfiles in the database folder

RaceHorology/MainWindow.xaml.cs, RaceHorologyLib/AppDataModel.cs, RaceHorologyLibTest/DSVAlpinDatabaseTests.cs, RaceHorologyLibTest/TestUtilities.cs
Introduced interface Close() for database
Added tests
Wired in main application
=> Solves #167 Close File Issues

RaceHorologyLib/DSVCalculations.cs
=> Fix crash in DSV Calculation

RaceHorology/ALGEDebugDlg.xaml, RaceHorology/RaceConfigurationSaveDlg.xaml, RaceHorology/RaceConfigurationSaveDlg.xaml.cs, RaceHorology/RaceHorology.csproj, RaceHorology/RaceUC.xaml, RaceHorology/RaceUC.xaml.cs, RaceHorologyLib/RaceConfiguration.cs, RaceHorologyLibTest/RaceConfigurationTest.cs, RaceHorologyLibTest/RaceHorologyLibTest.csproj, RaceHorologyLibTest/raceconfigpresets/DSV Erwachsene.preset, RaceHorologyLibTest/raceconfigpresets/FIS Rennen.preset
issue #233: Erzeugen und Ändern von Default-Rennkonfigurationen
issue #235: Verwendete Rennkonfiguration soll engezeigt werden
=> 193 Templateverbesserungen, Part 2

RaceHorology/RaceUC.xaml, RaceHorology/RaceUC.xaml.cs, RaceHorologyLibTest/RaceHorologyLibTest.csproj, RaceHorologyLibTest/TimeCalculationTest.cs
Platzoptimierungen (issue #239)
Eingabe von 1/10.000s möglich (issue #238)
=> Zeitnahmeverbesserungen - Manuelle Eingabe

RaceHorology/RaceUC.xaml
Vertikale Aufteilung für die Listen auf dem Zeitnahmebildschirm verbessert.
=> kleinere Platzoptimierung

RaceHorology/StartNumbersUC.xaml.cs
=> #260 Startnummerverlosung berücksichtigt "ab Nr" nicht

RaceHorology/CompetitionUC.xaml, RaceHorology/DSVImportUC.xaml, RaceHorology/DSVImportUC.xaml.cs, RaceHorology/FISImportUC.xaml, RaceHorology/FISImportUC.xaml.cs, RaceHorology/UIUtilities.cs
Bei dem FIS / DSV Import ist eine ComboBox, die die Spalte auswählt, in der gesucht werden soll.
Weiterhin wird der Text in der Suchtextbox bei einfachem Rein-Klicken ausgewählt, sodass man sofort mit der Suche loslegen kann.
=> 283 Einschränkung der Suchfelder bei der Erfassung der FIS/DSV Teilnehmer

RaceHorologyLib/AppDataModelViews.cs
=> Points will need to be updated after DSV Point Calculation has been updated

RaceHorologyLib/ALGETdC8001TimeMeasurement.cs, RaceHorologyLib/DSVExport.cs, RaceHorologyLib/PDFReports.cs
=> add TdC 8000 also to all reports and listings

RaceHorology/MainWindow.xaml, RaceHorology/MainWindow.xaml.cs
make close database only available when one is open, otherwise grey out
fixes #316
=> implement application closure

Documents/IconsAndPictures/colorcodes.txt, RaceHorology/RaceListsUC.xaml, RaceHorology/RaceUC.xaml, RaceHorologyLib/ALGETdC8001TimeMeasurement.cs, RaceHorologyLib/AppDataModel.cs, RaceHorologyLib/AppDataModelDataTypes.cs, RaceHorologyLib/AppDataModelViews.cs, RaceHorologyLib/LiveTimingMeasurement.cs
- Farbiges Hinterlegen der Teilnehmer, die an der ALGE aktiv sind für folgende Listen:
- Am Start
- Im Lauf
- Bugfix: Farbiges Markieren des eingefahrenen Rennläufers in den Ergebnislisten
=> Zeitnahmeverbesserungen

RaceHorologyLib/DSVExport.cs, RaceHorologyLibTest/DSVExportTest.cs
=> DSV Export ist auch bei "Nicht-Punkterennen" möglich

RaceHorology/App.config, RaceHorology/Properties/Settings.Designer.cs, RaceHorology/Properties/Settings.settings, RaceHorology/RaceListsUC.xaml.cs, RaceHorology/RaceUC.xaml.cs, RaceHorology/UIUtilities.cs
Aktuelle Sichtbarkeit wird als Applikationssetting gespeichert
=> Möglichkeit Spalten in Tabellen ein und auszublenden

RaceHorology/ExportResultDlg.xaml, RaceHorology/ExportResultDlg.xaml.cs, RaceHorology/ExportUI.cs, RaceHorology/MainWindow.xaml, RaceHorology/MainWindow.xaml.cs, RaceHorology/RaceHorology.csproj, RaceHorology/RaceListsUC.xaml, RaceHorology/RaceListsUC.xaml.cs, RaceHorologyLib/Export.cs, RaceHorologyLibTest/ExportTest.cs
- Alpenhunde Startlistenexport
- View Export bei der Liste
- Datenexport (alle Renndaten) via Menu
=> Export Verbesserungen

RaceHorologyLib/PDFReports.cs
to brand the pdfs also not directly visible
@svenflossmann Please check and approve if ok.
=> add some metadata to the created PDFs

.github/workflows/main.yml
=> add signing to workflow

RaceHorology/CompetitionUC.xaml, RaceHorology/CompetitionUC.xaml.cs, RaceHorology/DSVImportUC.xaml, RaceHorology/FISImportUC.xaml
fixes #297 
in addition, enhanced the way all 3 clear buttons in this view works
=> add clear button to participant search field

RaceHorology/App.config, RaceHorology/LICENSES_THIRD_PARTY.txt, RaceHorology/MainWindow.xaml, RaceHorology/MainWindow.xaml.cs, RaceHorology/Properties/Settings.Designer.cs, RaceHorology/RaceHorology.csproj, RaceHorology/RaceHorologyCommands.cs, RaceHorology/Settings.xaml, RaceHorology/Settings.xaml.cs, RaceHorology/packages.config
need to create a final webserver to load the xml from later on before release
=> introduce automatic update feature (first beta). 

RaceHorologyLib/COMPortViewModel.cs
=> do not crash application when COM Port is duplicated

.github/workflows/main.yml
and in addition update the workflow version to the current latest one
=> enhance pre-release notes to add more details

RaceHorology/MainWindow.xaml.cs, RaceHorologyLib/DSVAlpin2HTTPServer.cs
=> allow automatic restart when network changes

RaceHorology/MainWindow.xaml.cs
=> Fix crash for second RH instance opening a file

RaceHorologyLib/AppDataModel.cs, RaceHorologyLib/RaceHorologyLib.csproj, RaceHorologyLib/raceconfigpresets/Vielseitigkeit (Nicht-Punkte).preset, RaceHorologyLib/raceconfigpresets/Vielseitigkeit (Punkte).preset, RaceHorologySetup/Product.wxs
=> Feature: Unterstützung für Vielseitigkeit (Punkte) und Vielseitigkeit (Nicht-Punkte)

RaceHorologySetup/Product.wxs
=> Bugfix: Der Installer entfernt nun die Verknüpfung zum Programm nicht mehr bei einem Upgrade

RaceHorology/MainWindow.xaml.cs, RaceHorologyLib/MicrogateV1TimeMeasurement.cs, RaceHorologyLib/MicrogateV2TimeMeasurement.cs
additionally also adaption of indentation in implementation of Microgate V2 protocols to be conformal with project standard.
=> add online timing for Microgates Racetime 2

RaceHorologyLib/ALGETdC8001TimeMeasurement.cs
=> ignore Canceled Serial Messages from TdC in Memo Mode

RaceHorology/MainWindow.xaml, RaceHorology/MainWindow.xaml.cs, RaceHorology/RaceHorologyCommands.cs
=> Add WhatsApp Link to Help Menu

RaceHorology/TimingDeviceAlpenhundeUC.xaml, RaceHorology/TimingDeviceAlpenhundeUC.xaml.cs, RaceHorologyLib/TimingDeviceAlpenhunde.cs
- Display connected device correctly
- Send restart instead of synchronize
=> Fix small issues with Alpenhunde
